package com.example.hopes.feature.detail.presentation.content
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import com.example.hopes.R
import com.example.hopes.core.designsystem.AppSpacing
import com.example.hopes.core.designsystem.component.HopesScaffold
import com.example.hopes.core.designsystem.component.HopesSurfaceCard
import com.example.hopes.feature.auth.presentation.component.FigmaAuthTextField
import com.example.hopes.feature.detail.presentation.DetailScreenEvent
import com.example.hopes.feature.detail.presentation.DetailUiState
import com.example.hopes.navigation.HopesDestination
@Composable fun ChatDetailScreenContent(uiState:DetailUiState,onEvent:(DetailScreenEvent)->Unit,onNavigate:(HopesDestination)->Unit){val conversation=uiState.conversation;HopesScaffold(HopesDestination.Chat,onNavigate){inner->Column(Modifier.fillMaxSize().padding(inner).padding(horizontal=AppSpacing.ScreenHorizontal,vertical=24.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){HopesSurfaceCard{Text(conversation?.question?:stringResource(R.string.chat_detail_title))};HopesSurfaceCard{Text(stringResource(R.string.chat_answer_label));Text(stringResource(R.string.chat_detail_answer))};conversation?.replies?.forEach{reply->HopesSurfaceCard{Text(reply)}};FigmaAuthTextField(conversation?.replyDraft.orEmpty(),{onEvent(DetailScreenEvent.ReplyChanged(it))},R.string.chat_additional_question,modifier=Modifier.fillMaxWidth());Text(stringResource(R.string.chat_send),Modifier.fillMaxWidth())}}}
